:page-category: tech
:page-date: 2018-07-23
:page-tags: tech, wiki, sad, asciidoc
= using Asciidoc

You can author pages in Asciidoc - but sadly a lot of things don't work.

I might remove Asciidoc entirely soon - it's falling a bit behind alas.

= heading

== sub heading

== table

Tables are part of why I like asciidoc.  But the JS one does some but not all features - cells spanning rows isn't quite right.  See http://asciidoc.org/userguide.html#_tables for the full set of what the spec allows.

[cols="1,1,3", options="header"]
|===
| Email | Person | Notes
| foo@bar.com
>s| foo
| just stuff

| dave@smith.com
| dave
a| * embedded asciidoc!
* and code:
----
(def code (+ a b))
----

| spanning rows and cols
2.2+^.^| not working properly!

columns span, but not rows
| second row 
|===

== source code

Highlighting not working either sadly

[source,java]
----
  private Function<Throwable, Either<ApiError, UUID>> recoverFromHttpStatusCodeException() {
    return x -> Match(x).of(
            Case($(instanceOf(HttpClientErrorException.class)),
                    this::buildValidationError)
    );
  }
----

== diagrams - don't work

[plantuml, format=svg]
....
Alice -> Bob: Authentication Request
Bob --> Alice: Authentication Response

Alice -> Bob: Another authentication Request
Alice <-- Bob: another authentication Response
....
